In [7]:
import numpy as np
import pickle
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import os
import scipy.cluster.hierarchy as shc
import seaborn as sns
from sklearn.preprocessing import normalize
from sklearn.cluster import AgglomerativeClustering
from scipy import ndimage, stats
import sys
code_path = r'U:\Work_PT\Code\2p_analysis_development\2panalysis\Helpers'
sys.path.insert(0, code_path) 
import ROI_mod
import post_analysis_core as pac

In [82]:
def create_datalists(curr_rois, datalist):
    datalist = []
    for roi in curr_rois:
          entry = {
               'uniq_id': roi.uniq_id,
               # 'independent_var': getattr(roi, 'independent_var', np.nan),
               # 'interpolated_traces': getattr(roi, 'interpolated_traces_epochs', np.nan),
               # 'interpolated_time': getattr(roi, 'interpolated_time', np.nan),
               'max_resp_all_epochs': getattr(roi, 'max_resp_all_epochs', np.nan),
               'max_resp_all_epoch_on':getattr(roi, 'max_resp_all_epochs_ON', np.nan),
               'max_resp_all_epoch_off':getattr(roi, 'max_resp_all_epochs_OFF', np.nan),
               'freq_power_epochs': getattr(roi, 'freq_power_epochs', np.nan),  # Use np.nan if attribute does not exist
               'FlyId': roi.experiment_info['FlyID'],  # Include FlyId attribute
               # 'ind var values': getattr(roi, 'independent_var_vals', np.nan),  # Include independent_var_vals attribute
               'treatment': roi.experiment_info['treatment'],
               'category': roi.category[-1],
               'reliability_PD': getattr(roi, 'reliability_PD', np.nan), 
               'reliability_ON': getattr(roi, 'reliability_PD_ON', np.nan),
               'reliability_OFF': getattr(roi, 'reliability_PD_OFF', np.nan),
               'DSI_ON': getattr(roi, 'DSI_ON', np.nan),
               'DSI_OFF': getattr(roi, 'DSI_OFF', np.nan),
               'CS': getattr(roi, 'CS', np.nan),
               'CSI': getattr(roi, 'CSI',np.nan),
               'whole_traces_all_epochsTrials': getattr(roi, 'whole_traces_all_epochsTrials', np.nan), 
               'df_trace': getattr(roi, 'df_trace', np.nan), 
               'dir_max_resp': getattr(roi, 'dir_max_resp', np.nan),
               'PD_ON': getattr(roi, 'PD_ON', np.nan),
               'PD_OFF': getattr(roi, 'PD_OFF', np.nan),
               'direction_vector':getattr(roi, 'direction_vector', np.nan)
          }
          datalist.append(entry)
     
          return datalist

In [91]:
datapath = r'U:\Work_PT\2p_data\Gcamp_exp\data_processed'

# dataset = '231204_PT_fly1-TSeries-12042023_G8f-069-cycle_1_cycle0_DriftingStripe_4sec_6sec_edges_80deg_degAz_degEl_Sequential_LumDec_8D_ONEDGEFIRST_80sec.pickle'
datasets_to_load = os.listdir(datapath)
for idx, dataset in enumerate(datasets_to_load):
     load_path = os.path.join(datapath, dataset)
     load_path = open(load_path, 'rb')
     workspace = pickle.load(load_path)
     curr_rois = workspace['final_rois']
     data= []
     for roi in curr_rois:
          entry = {
               'uniq_id': roi.uniq_id,
               # 'independent_var': getattr(roi, 'independent_var', np.nan),
               # 'interpolated_traces': getattr(roi, 'interpolated_traces_epochs', np.nan),
               # 'interpolated_time': getattr(roi, 'interpolated_time', np.nan),
               'max_resp_all_epochs': getattr(roi, 'max_resp_all_epochs', np.nan),
               'max_resp_all_epoch_on':getattr(roi, 'max_resp_all_epochs_ON', np.nan),
               'max_resp_all_epoch_off':getattr(roi, 'max_resp_all_epochs_OFF', np.nan),
               'freq_power_epochs': getattr(roi, 'freq_power_epochs', np.nan),  # Use np.nan if attribute does not exist
               'FlyId': roi.experiment_info['FlyID'],  # Include FlyId attribute
               # 'ind var values': getattr(roi, 'independent_var_vals', np.nan),  # Include independent_var_vals attribute
               'treatment': roi.experiment_info['treatment'],
               'category': roi.category[-1],
               'reliability_PD': getattr(roi, 'reliability_PD', np.nan), 
               'reliability_ON': getattr(roi, 'reliability_PD_ON', np.nan),
               'reliability_OFF': getattr(roi, 'reliability_PD_OFF', np.nan),
               'DSI_ON': getattr(roi, 'DSI_ON', np.nan),
               'DSI_OFF': getattr(roi, 'DSI_OFF', np.nan),
               'CS': getattr(roi, 'CS', np.nan),
               'CSI': getattr(roi, 'CSI',np.nan),
               'whole_traces_all_epochsTrials': getattr(roi, 'whole_traces_all_epochsTrials', np.nan), 
               'df_trace': getattr(roi, 'df_trace', np.nan), 
               'dir_max_resp': getattr(roi, 'dir_max_resp', np.nan),
               'PD_ON': getattr(roi, 'PD_ON', np.nan),
               'PD_OFF': getattr(roi, 'PD_OFF', np.nan),
               'direction_vector':getattr(roi, 'direction_vector', np.nan)
          }
          # data.append(entry)
          df = pd.concat(list(entry), axis = 1)
          

     # Convert the data list to a pandas DataFrame

TypeError: cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid

In [9]:
new_df = df.copy()
new_df = new_df[new_df.reliability_PD >= 0.4]
new_df.head()

,uniq_id,max_resp_all_epochs,max_resp_all_epoch_on,max_resp_all_epoch_off,freq_power_epochs,FlyId,treatment,category,reliability_PD,reliability_ON,...,DSI_ON,DSI_OFF,CS,CSI,whole_traces_all_epochsTrials,df_trace,dir_max_resp,PD_ON,PD_OFF,direction_vector
0,2614117993008,NaN,"[0.015258148471138756, 0.16643947789705793, 0....","[0.9185820865237528, 0.3469386200347039, 0.510...",NaN,231204_PT_fly1,control_heterozygous,No_category,0.722672,0.169905,...,0.380489,0.237159,OFF,0.983389,"{0: [[-0.25714910947580255, -0.027342380839394...","[-0.029628154491044056, -0.046882042735162624,...",180.0,68.585911,153.636328,"[180.0, 0.0, 270.0, 90.0, 225.0, 45.0, 135.0, ..."
3,2614106588880,NaN,"[0.40628177462944653, 0.8154720643232652, 0.39...","[0.26837779296277314, 2.360405842026292, 0.170...",NaN,231204_PT_fly1,control_heterozygous,A,0.655806,0.404497,...,0.135886,0.293222,OFF,0.654520,"{0: [[0.10441450167336683, -0.2304018945833509...","[-0.605270823787234, -0.2385333801311458, -0.1...",0.0,308.383029,348.278624,"[180.0, 0.0, 270.0, 90.0, 225.0, 45.0, 135.0, ..."
4,2616277859872,NaN,"[0.16946204434823392, 0.4790930965675886, 0.35...","[0.7381769408979688, 0.6713976409683959, 0.388...",NaN,231204_PT_fly1,control_heterozygous,No_category,0.549585,0.296797,...,0.199855,0.149438,OFF,0.660230,"{0: [[-0.1456325003441072, 0.06985940281427713...","[-0.36377607801596645, -0.39507965759471236, 0...",90.0,341.514040,104.620632,"[180.0, 0.0, 270.0, 90.0, 225.0, 45.0, 135.0, ..."
5,2616277859680,NaN,"[0.37232787400851797, 0.41455510404322754, 0.1...","[0.3506204595210116, 1.4510372058000218, 0.356...",NaN,231204_PT_fly1,control_heterozygous,No_category,0.628512,0.092994,...,0.036957,0.305231,OFF,0.849050,"{0: [[-0.5366907469019752, 0.17539529275477933...","[-0.413846076489992, 0.16383683230261234, 0.17...",90.0,155.990276,32.296687,"[180.0, 0.0, 270.0, 90.0, 225.0, 45.0, 135.0, ..."
6,2616277860304,NaN,"[0.46763997733758056, 0.6344858546805187, 0.30...","[0.41374095598922533, 0.501811524734957, 0.728...",NaN,231204_PT_fly1,control_heterozygous,No_category,0.472776,0.407258,...,0.030626,0.092651,OFF,0.620219,"{0: [[0.24414038421082218, -0.0227008688011962...","[-0.4289408422452692, -0.46074655726869346, -0...",90.0,57.622090,75.855664,"[180.0, 0.0, 270.0, 90.0, 225.0, 45.0, 135.0, ..."

In [27]:
new_df.max_resp_all_epoch_on

0     [0.015258148471138756, 0.16643947789705793, 0....
3     [0.40628177462944653, 0.8154720643232652, 0.39...
4     [0.16946204434823392, 0.4790930965675886, 0.35...
5     [0.37232787400851797, 0.41455510404322754, 0.1...
6     [0.46763997733758056, 0.6344858546805187, 0.30...
7     [0.9306158882471509, 1.0817864721874935, 0.963...
8     [0.5280927751153179, 0.3256819358704532, 0.366...
9     [0.2959685075993535, 0.2719561828881905, 0.467...
10    [0.24244953568465852, 0.1978964287124814, 0.21...
12    [0.40186974754139243, 0.44023973213333567, 0.3...
14    [0.49754495428782336, 0.3342096894159297, 0.24...
15    [0.8669614502016826, 0.6867465870420582, 0.271...
16    [0.5366084293353495, 0.46068612470246945, 0.20...
17    [0.2738302109508909, 0.9600135343900924, 0.293...
18    [1.01684969017736, 2.694002084632201, 0.329207...
19    [0.27128175682298444, 2.374589009256775, 0.214...
20    [0.40100517468521696, 0.8995005130504697, 2.25...
21    [0.31974852531268494, 0.743217270121763, 1.758...
22    [0.31002253309397065, 0.4193427655969059, 0.35...
23    [0.5146305149728597, 0.4680374594604851, 0.669...
24    [0.27740258348290814, 0.25660395703135813, 0.3...
25    [1.1365636561308334, 1.7935630164995355, 1.609...
26    [0.23238239832590224, 0.868676786479768, 1.232...
27    [0.39840332891405567, 0.9553672160609049, 2.73...
28    [0.4203749593714745, 0.7614876571203923, 1.957...
29    [0.45903435980609336, 1.585785932353457, 1.550...
Name: max_resp_all_epoch_on, dtype: object

In [81]:
pldf = new_df[['PD_ON', 'PD_OFF','category', 'CS', 'max_resp_all_epoch_on', 'max_resp_all_epoch_off']]
len(pldf.iloc[0,-1])

8

In [60]:
df.iloc[1:5,-5]

1    [0.08047974959048752, 0.7020553208632717, 0.98...
2    [-0.20957577722075288, 0.6845545399661971, 0.1...
3    [-0.605270823787234, -0.2385333801311458, -0.1...
4    [-0.36377607801596645, -0.39507965759471236, 0...
Name: df_trace, dtype: object

In [1]:
fig = plt.figure()
fig, ax = plt.subplots()
m = []
for k in range(0, len(pldf)):
    m.append(df.iloc[k,-5])
l = np.mean(m, axis=0)
ax.plot(l[0:50])

NameError: name 'plt' is not defined

In [48]:
df.head()

,uniq_id,max_resp_all_epochs,max_resp_all_epoch_on,max_resp_all_epoch_off,freq_power_epochs,FlyId,treatment,category,reliability_PD,reliability_ON,...,DSI_ON,DSI_OFF,CS,CSI,whole_traces_all_epochsTrials,df_trace,dir_max_resp,PD_ON,PD_OFF,direction_vector
0,2614117993008,NaN,"[0.015258148471138756, 0.16643947789705793, 0....","[0.9185820865237528, 0.3469386200347039, 0.510...",NaN,231204_PT_fly1,control_heterozygous,No_category,0.722672,0.169905,...,0.380489,0.237159,OFF,0.983389,"{0: [[-0.25714910947580255, -0.027342380839394...","[-0.029628154491044056, -0.046882042735162624,...",180.0,68.585911,153.636328,"[180.0, 0.0, 270.0, 90.0, 225.0, 45.0, 135.0, ..."
1,2614117992672,NaN,"[0.510832302358285, 0.2989096176794498, 0.2164...","[1.3294082270553513, 0.3593466444848019, 0.202...",NaN,231204_PT_fly1,control_heterozygous,B,0.167741,0.363023,...,0.214120,0.405572,OFF,0.615745,"{0: [[-0.2530564603672531, -0.3533918196063603...","[0.08047974959048752, 0.7020553208632717, 0.98...",180.0,116.400151,146.641791,"[180.0, 0.0, 270.0, 90.0, 225.0, 45.0, 135.0, ..."
2,2614104628320,NaN,"[0.5634748402928379, 0.4781822664411412, 0.224...","[1.474014318769536, 0.2672862559746278, 0.3318...",NaN,231204_PT_fly1,control_heterozygous,B,0.281655,0.244904,...,0.201359,0.431214,OFF,0.617728,"{0: [[-0.244156757823908, 0.05416026465018636,...","[-0.20957577722075288, 0.6845545399661971, 0.1...",180.0,124.972187,158.166247,"[180.0, 0.0, 270.0, 90.0, 225.0, 45.0, 135.0, ..."
3,2614106588880,NaN,"[0.40628177462944653, 0.8154720643232652, 0.39...","[0.26837779296277314, 2.360405842026292, 0.170...",NaN,231204_PT_fly1,control_heterozygous,A,0.655806,0.404497,...,0.135886,0.293222,OFF,0.654520,"{0: [[0.10441450167336683, -0.2304018945833509...","[-0.605270823787234, -0.2385333801311458, -0.1...",0.0,308.383029,348.278624,"[180.0, 0.0, 270.0, 90.0, 225.0, 45.0, 135.0, ..."
4,2616277859872,NaN,"[0.16946204434823392, 0.4790930965675886, 0.35...","[0.7381769408979688, 0.6713976409683959, 0.388...",NaN,231204_PT_fly1,control_heterozygous,No_category,0.549585,0.296797,...,0.199855,0.149438,OFF,0.660230,"{0: [[-0.1456325003441072, 0.06985940281427713...","[-0.36377607801596645, -0.39507965759471236, 0...",90.0,341.514040,104.620632,"[180.0, 0.0, 270.0, 90.0, 225.0, 45.0, 135.0, ..."